spring:
      datasource:
          driver-class-name: com.mysql.jdbc.Driver
          #url: jdbc:mysql://222.25.188.1:50173/tl
#          url: jdbc:mysql://jqhu.top:3306/tl?characterEncoding=utf-8&useSSL=false
          url: jdbc:mysql://125.76.159.135:3306/tl?characterEncoding=utf-8&useSSL=false
#          url: jdbc:mysql://localhost:3306/tl?characterEncoding=utf-8&useSSL=false
          username: root
          password: xdstone001
#            password: hjq951019
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: false
#        open-in-view: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /