spring:
      datasource:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://222.25.188.1:50173/tl
          username: root
          password: 123456

      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        open-in-view: true
server:
  port: 8080