spring:
      datasource:
          driver-class-name: org.mariadb.jdbc.Driver
          url: jdbc:mysql://193.112.64.181:3306/tl
          username: tl
          password: 123456

      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
